Add draw button
fortyoneeight/variant64 pull request #125
Opened 2022-12-16 15:28 UTC by benshumaker

Closes: #57
<img width="1004" alt="Screen Shot 2022-12-16 at 10 28 19 AM" src="https://user-images.githubusercontent.com/88255374/208132005-8da47491-481a-4bb6-ae53-a78ed092b64a.png">
<img width="1040" alt="Screen Shot 2022-12-16 at 10 28 04 AM" src="https://user-images.githubusercontent.com/88255374/208132021-fc82b704-d517-4657-82b8-084927286c65.png">

2022-12-16 20:53 UTC, izakfr requested changes

2022-12-16 20:53 UTC, izakfr commented on frontend/packages/web/src/components/features/DrawButton/DrawButton.tsx
> +  const handleDrawClick = (accepted: boolean) => {
Can we change this to `handleDrawOnClick`

2022-12-16 20:53 UTC, izakfr commented on frontend/packages/web/src/components/features/DrawButton/DrawButton.tsx
> +    if (!drawStates) return 'game_not_started';
Can you make an enum for draw state?
States would be:
```
NONE
INCOMING_DRAW
OUTGOING_DRAW
```

2022-12-16 20:53 UTC, izakfr commented on frontend/packages/web/src/components/features/DrawButton/DrawButton.tsx
> +    for (const id in game.approved_draw_players) {
you can solve this with an map call:
```
let approvals = Object.values(game.approved_draw_players)
return approvals.filter(val => val).length / approvals.length
```

2022-12-16 20:53 UTC, izakfr commented on frontend/packages/web/src/components/pages/hompage-service.ts
> +  drawGame(accepted: boolean, gameID: string, playerID: string) {
can you change the function parameter  to `approved` from `accepted`

2022-12-17 05:27 UTC, jbsummoner commented on frontend/packages/web/src/components/features/DrawButton/DrawButton.tsx
> +    for (const id in game.approved_draw_players) {
we prob couldve named this(game.approved_draw_players) @izakfr

2022-12-17 20:37 UTC, izakfr approved these changes
Looks good, thanks!

2022-12-17 21:32 UTC, merged