Feature152 render timer updates
fortyoneeight/variant64 pull request #163
Opened 2023-01-11 23:37 UTC by benshumaker

Closes: #152 

I also added a couple minor style touches and form improvements.

2023-01-12 14:43 UTC, izakfr requested changes

2023-01-12 14:43 UTC, izakfr commented on frontend/packages/web/src/components/features/CreateRoomForm/CreateRoomForm.tsx
> -  useEffect(() => {
Does this just not need to happen anymore?

2023-01-12 14:43 UTC, izakfr commented on frontend/packages/web/src/components/features/CreateRoomForm/CreateRoomForm.tsx
> +    console.log('Ping end of handle submit: ' + roomForm.name);
Can we try and keep console logs to a minimum?

2023-01-12 14:43 UTC, izakfr commented on frontend/packages/web/src/components/features/GameplayButtons/DrawButton.tsx
> +    console.log('PING handleDrawOnClick');
Same as above.

2023-01-12 14:43 UTC, izakfr commented on frontend/packages/web/src/components/features/GameplayButtons/GameplayButtons.tsx
> +          <DrawButton />
Good fix 👍

2023-01-12 14:43 UTC, izakfr commented on frontend/packages/web/src/components/features/OnboardingForm/OnboardingForm.tsx
> +  useEffect(() => {
I saw similar code to this in CreateRoomForm.ts. Is is worth making data entry like this it's own component?

2023-01-12 14:43 UTC, izakfr commented on frontend/packages/web/src/components/features/PlayerInfo/PlayerInfo.tsx
> +interface PlayerCardProps {
Nice!

2023-01-12 15:25 UTC, benshumaker commented on frontend/packages/web/src/components/features/CreateRoomForm/CreateRoomForm.tsx
> -  useEffect(() => {
I honestly don't remember changing this. Maybe I moved it? Idk. Just looking at it, I don't think the CreateRoomForm needs to update roomsList when it loads. We only use that info in another component, which already pulls the most recent info when it loads.

2023-01-12 15:26 UTC, benshumaker commented on frontend/packages/web/src/components/features/OnboardingForm/OnboardingForm.tsx
> +  useEffect(() => {
Perhaps. I'm inclined not to, since it's only used in two places and they're not exactly the same. For more context, I added these so pressing the Enter key would auto-submit forms.

2023-01-13 15:28 UTC, izakfr approved these changes
Thank you for the updates!

2023-01-13 15:29 UTC, merged