Add websocket updates for room list
fortyoneeight/variant64 pull request #184
Opened 2023-01-15 22:04 UTC by izakfr

Closes: #183

2023-01-15 22:25 UTC, benshumaker requested changes
Mostly good. I have a few minor comments and questions

2023-01-15 22:25 UTC, benshumaker commented on frontend/packages/web/src/components/features/Subscription/Subscription.tsx
> +    setRoomMap({ ...roomMap, ...(message.data.room_map as RoomMap) });
Why is this message.data.room_map but the other handlers just access message.data?

2023-01-15 22:25 UTC, benshumaker commented on frontend/packages/web/src/components/features/Subscription/Subscription.tsx
> +          handleRoomMessage(messageState);
Nice

2023-01-15 22:25 UTC, benshumaker commented on frontend/packages/web/src/components/features/Subscription/Subscription.tsx
> +import merge from 'ts-deepmerge';
Why did you add ts-deepmerge? I couldn't even find where you used merge...

2023-01-15 22:25 UTC, benshumaker commented on frontend/packages/web/src/components/features/RoomList/RoomList.tsx
> +          if (r.players[player.id]) {
Why do we need to check if they're already in the room? Wouldn't that imply the aren't on this screen?

2023-01-15 22:25 UTC, benshumaker commented on frontend/packages/web/src/components/features/RoomList/RoomList.tsx
> +    return () => {
Does a useEffect return function call when the component un-renders?

2023-01-16 00:53 UTC, izakfr commented on frontend/packages/web/src/components/features/Subscription/Subscription.tsx
> +    setRoomMap({ ...roomMap, ...(message.data.room_map as RoomMap) });
Discussed this offline.

2023-01-16 00:58 UTC, benshumaker approved these changes
Big Win

2023-01-16 15:32 UTC, closed without merging