[#104] Add Endgame Display
fortyoneeight/variant64 pull request #186
Opened 2023-01-16 21:04 UTC by benshumaker

Closes: #104

2023-01-16 21:41 UTC, izakfr requested changes

2023-01-16 21:41 UTC, izakfr commented on frontend/packages/web/src/components/features/EndgameOverlay/EndgameOverlay.tsx
> +  useEffect(() => {
Can you combine these two things to be one switch statement? This component will only re-render on the game changing anyway so this useEffect is unnecessary.

2023-01-16 22:21 UTC, benshumaker commented on frontend/packages/web/src/components/features/EndgameOverlay/EndgameOverlay.tsx
> +  useEffect(() => {
I changed this. Unsure if this is what you had in mind. It's down to 1 switch, which is nice. When I tried to do it without a useEffect, the buttons would never render even when the game.state finished.

2023-01-17 01:26 UTC, izakfr approved these changes

2023-01-17 01:26 UTC, izakfr commented on frontend/packages/web/src/components/features/EndgameOverlay/EndgameOverlay.tsx
> +  useEffect(() => {
This looks good, thanks!

2023-01-17 01:39 UTC, merged