Add ws unsubscribe commands
fortyoneeight/variant64 pull request #190
Opened 2023-01-16 21:37 UTC by izakfr

Closes: #185

2023-01-16 22:29 UTC, benshumaker requested changes
I just have a couple small notes

2023-01-16 22:29 UTC, benshumaker commented on frontend/packages/web/src/components/features/Subscription/Subscription.tsx
> +      }
This looks strange. It seems like the first if statement would exclude the else statement from happening, so it would never unsubscribe. Is that true?

2023-01-16 22:29 UTC, benshumaker commented on frontend/packages/web/src/services/websocket/types.ts
> +  SUBSCRIBE = 'subscribe',
If the websocket actions are just SUBSCRIBE and UNSUBSCRIBE now, do we even need the other values below in this enum?

2023-01-17 01:25 UTC, izakfr commented on frontend/packages/web/src/components/features/Subscription/Subscription.tsx
> +      }
if roomMapSub is undefined nothing happens
if roomMapSub is true we subscribe
if roomMapSub is false we unsubscribe

there was an issue with firefox trying to unsubscribe at startup due to it being false, so I initialized it as undefined

2023-01-17 01:25 UTC, izakfr commented on frontend/packages/web/src/services/websocket/types.ts
> +  SUBSCRIBE = 'subscribe',
removed, my bad

2023-01-17 01:30 UTC, benshumaker approved these changes
Remember when you made me that steak? That was a good day.

2023-01-17 01:31 UTC, merged