[#305] add home and pregame mobile styles
fortyoneeight/variant64 pull request #308
Opened 2023-02-10 01:29 UTC by benshumaker

Closes: #305 
Closes: #306

2023-02-10 15:23 UTC, izakfr requested changes

2023-02-10 15:23 UTC, izakfr commented on frontend/packages/web/src/components/features/CreateRoomForm/CreateRoomForm.tsx
> +        <NonMobileWhiteBackgroundText>Gamemode:</NonMobileWhiteBackgroundText>
Is there a better way to do / name this. `NonMobileWhiteBackgroundText` doesn't look right to me.

2023-02-10 15:23 UTC, izakfr commented on frontend/packages/web/src/components/pages/Homepage/Homepage.styled.tsx
> +export const HomepageTopContainer = styled.div`
Can you name these better? Something like HomepageOuterContainer and HomepageInnerContainer?

2023-02-10 15:23 UTC, izakfr commented on frontend/packages/web/src/components/pages/Homepage/Homepage.styled.tsx
> +export const HomepageTopContainer = styled.div`
Anything like ...V2 or Second... is a trigger to me lol

2023-02-10 16:32 UTC, benshumaker commented
I am going to revise this PR so you don't have to scroll to see the full game mode preview.

2023-02-11 20:53 UTC, benshumaker commented on frontend/packages/web/src/components/features/CreateRoomForm/CreateRoomForm.tsx
> +        <NonMobileWhiteBackgroundText>Gamemode:</NonMobileWhiteBackgroundText>
I'll find a cleaner way to do this later. Soon I'll be doing a component/style refactor. I thought of a cleaner prop-based way to do this.

2023-02-11 20:56 UTC, izakfr approved these changes
I have very closely analyzed the contents of this pull request.

2023-02-11 20:58 UTC, merged